package com.mcssoft.racedaybasic.domain.dto2

data class BaseDto2(
    val runners: List<RunnerDto>,
)
//    val allIn: Boolean,
//    val allowBundle: Boolean,
//    val allowFixedOddsPlace: Boolean,
//    val allowMulti: Boolean,
//    val allowParimutuelPlace: Boolean,
//    val apprenticesCanClaim: Boolean,
//    val betTypes: List<Any>,
//    val broadcastChannel: Any,
//    val broadcastChannels: List<Any>,
//    val cashOutEligibility: String,
//    val dividends: List<Dividend>,
//    val fixedOddsOnlineBetting: Boolean,
//    val fixedOddsUpdateTime: String,
//    val hasEarlySpeedRatings: Boolean,
//    val hasFixedOdds: Boolean,
//    val hasForm: Boolean,
//    val hasParimutuel: Boolean,
//    val meeting: Meeting,
//    val multiLegApproximates: List<Any>,
//    val numberOfPlaces: Int,
//    val oddsUpdateTime: String,
//    val parimutuelPlaceStatus: String,
//    val pools: List<Pool>,
//    val prizeMoney: String,
//    val raceClassConditions: String,
//    val raceDistance: Int,
//    val raceName: String,
//    val raceNumber: Int,
//    val raceStartTime: String,
//    val raceStatus: String,
//    val ratings: List<Rating>,
//    val results: List<List<Int>>,
//    val sameRaceMultiMarkets: List<SameRaceMultiMarket>,
//    val skyRacing: SkyRacing,
//    val spectrumId: String,
//    val substitute: Int,
//    val tips: Tips,
//    val trackDirection: String,
//    val willHaveFixedOdds: Boolean
